services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: dating_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dating_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"     # RabbitMQ broker
      - "15672:15672"   # Management UI
    networks:
      - appnet
      
  gateway:
    build: ./gateway/Gateway.API
    container_name: dating_gateway
    ports:
      - "5000:80"
    depends_on:
      - auth
      - users
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - appnet

  auth:
    build: ./services/AuthService/AuthService.API
    container_name: dating_auth
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_AUTH_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    networks:
      - appnet

  users:
    build: ./services/UserService/UserService.API
    container_name: dating_users
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_DATING_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - appnet

  match:
    build: ./services/MatchService/MatchService.API
    container_name: dating_match
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_MATCH_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__User=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ__Pass=${RABBITMQ_DEFAULT_PASS}
    networks:
      - appnet
volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
