services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: dating_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dating_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"     # RabbitMQ broker
      - "15672:15672"   # Management UI
    networks:
      - appnet
      
  gateway:
    build: ./gateway/Gateway.API
    container_name: dating_gateway
    ports:
      - "5000:80"
    depends_on:
      - auth
      - users
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - appnet

  auth:
    build: ./services/AuthService/AuthService.API
    container_name: dating_auth
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_AUTH_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    networks:
      - appnet

  users:
    build: ./services/UserService/UserService.API
    container_name: dating_users
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_DATING_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - appnet

  match:
    build: ./services/MatchService/MatchService.API
    container_name: dating_match
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_MATCH_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__User=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ__Pass=${RABBITMQ_DEFAULT_PASS}
    networks:
      - appnet
  notify:
    build: ./services/NotificationService/NotificationService.API
    container_name: dating_notification
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=notification_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__User=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ__Pass=${RABBITMQ_DEFAULT_PASS}
    networks:
      - appnet
  messaging:
    build: ./services/MessagingService/MessagingService.API
    container_name: dating_messaging
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Postgres=Host=postgres;Database=messaging_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__User=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ__Pass=${RABBITMQ_DEFAULT_PASS}
    networks:
      - appnet
  ai-insights-service:
    build: ./services/AiInsightsService/AiInsightsService.API
    ports:
      - "5006:80"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_AI_INSIGHTS_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  purchase-service:
    build: ./services/PurchaseService/PurchaseService.API
    ports:
      - "5007:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_PURCHASE_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  moderation-service:
    build: ./services/ModerationService/ModerationService.API
    ports:
      - "5008:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_MODERATION_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
